### ISSUE TITLE
Using MkDocs from Github Actions with Material - Plugins not enabled?

### ISSUE THREAD

**Issue by dcaddick** [athackst/mkdocs-simple-plugin#466]
Hi, first time posting here in Github Issues.

I have managed to use MkDocs & Material via Github Actions to publish a website to Github pages.
And I will freely admit that I'm very dangerous and chiefly code with a chainsaw and sledge hammer...

What I'm finding difficult to understand is how the Plugins work?
In my Github workflow I have understood enough to install plugins via pip here:
[MakeDocsAction.yaml](https://github.com/dcaddick/gsd_public/blob/main/.github/workflows/MakeDocsAction.yaml)
But also curious as to whether or not I should be just able to "add" these to the list via the [requirements.txt](https://github.com/dcaddick/gsd_public/blob/main/requirements.txt) file?
requirements.txt

Anyway - getting them installed is one thing, easy enough, the hard part that I'm struggling with is getting them enabled?
See here for the mkdocs.yml in root:
[mydocs.yml](https://github.com/dcaddick/gsd_public/blob/main/mkdocs.yml)

The only ones I can get running are Search, Simple & Macros - am I doing something really dumb?
Snippet:

```
# Plugins
plugins:
  - search
  - simple
  #- techdocs-core
  #- glightbox
  #- social
  #- awesome-list
  #- table-reader
  #- img2fig
  #- mermaid2
  - macros
  # - minify
```

I've commented out the Plugins that keep erroring - here is an example of the error "Action"
[Action run - with error](https://github.com/dcaddick/gsd_public/actions/runs/3922014831)

![image](https://user-images.githubusercontent.com/19640455/212787417-3a921f08-567d-47d7-8a15-f59fe741df3b.png)

I've simply not worried about the Plugins errors and got on with creating the content and figured I'd get around to this at some stage.

Using pip I can consistently get the plugin to "install" but getting it enabled has consistently shown an error similar to this with just the name of the plug-in changing.

I figured it was just me doing something dumb?

**Comment by athackst** [comment]
Yeah, you just need to put them in your requirements.txt file

This action reads the requirements.txt file and installs all packages listed in there before running (see [entrypoint.sh](https://github.com/athackst/mkdocs-simple-plugin/blob/main/docker/entrypoint.sh) called in the action [Dockerfile](https://github.com/athackst/mkdocs-simple-plugin/blob/main/Dockerfile)) 

![image](https://user-images.githubusercontent.com/6098197/212791457-74296e92-77eb-4f7e-b733-0827b7f1eac1.png)

(1) shows all of the plugins that were installed into the action from requirements.txt

(2) It seems like you have `mkdocs-git-revision-date-plugin` but `mkdocs-git-revision-date-localized-plugin` is commented out in your requirements.txt file.  Is there a reason for that?

The action doesn't currently support another file/name for requirements, but that would be a pretty easy change.

There shouldn't be any need to "enable" a plugin - once it's installed it should be findable by mkdocs.  The plugins need to be installed within the action container, which is why your pip install lines aren't working the way you expect.  That installs things into the github workflow instance, but that's isolated from the action.

**Comment by dcaddick** [comment]
Thanks Allison,

So remove my "BS" from the actions, and just revert to using the Requirements.txt as the *only* place to call PLugins to be installed?

I have been back and forth trying to troubleshoot why I can get Plugins "installed" - but not "enabled" - this is why some parts are commented out.

From what you're saying I don't *need* to enable the plugins via my mkdocs.yml file?
[https://github.com/dcaddick/gsd_public/blob/main/mkdocs.yml](url)

**Comment by athackst** [comment]
> So remove my "BS" from the actions, and just revert to using the Requirements.txt as the only place to call PLugins to be installed?

Yes, the plugin should read from `requirements.txt` and install plugins accordingly.

A simple workflow should look something like this

```
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and push docs
        uses: athackst/mkdocs-simple-plugin@v2.2.0
```

> I have been back and forth trying to troubleshoot why I can get Plugins "installed" - but not "enabled" - this is why some parts are commented out.
>
> From what you're saying I don't need to enable the plugins via my mkdocs.yml file?
[https://github.com/dcaddick/gsd_public/blob/main/mkdocs.yml](https://github.com/athackst/mkdocs-simple-plugin/issues/url)

Ah, yes. You do need to add it to `mkdocs.yml` - I don't think I understood what you were talking about earlier.  Adding it to mkdocs.yml will tell mkdocs to call the hooks in the plugin (otherwise it wouldn't know what was installed).

**Comment by athackst** [comment]
Maybe a tip for testing:

The image published to docker is the same one as the action.  You can run it locally for testing

```bash
docker run --rm -it --network=host -v ${PWD}:/docs --user $(id -u):$(id -g) althack/mkdocs-simple-plugin
```

It should build and serve the site locally through the container

**Comment by dcaddick** [comment]
> Ah, yes. You do need to add it to `mkdocs.yml` - I don't think I understood what you were talking about earlier. Adding it to mkdocs.yml will tell mkdocs to call the hooks in the plugin (otherwise it wouldn't know what was installed).

So this is where I have been seeing the error come thru - not the actual install of the Plugins - but the "call to the hooks" and the subsequent detailed config has been the typical error point.

I've now cleaned out the PIP calls and kept it clean in the workflow - testing that now.
Will then move on to checking/updating reqs.txt - then after that back to seeing if "the hooks" work or still error out

**Comment by athackst** [comment]
It looks like the issue is that something is requiring numpy which apparently doesn't like python 3.11

![image](https://user-images.githubusercontent.com/6098197/212813321-2aa71df5-0c6c-4b3a-98df-7c5d05c6744d.png)

Try changing to v2.1.3 instead of v2.2.0

**Comment by dcaddick** [comment]
So after the numpy error - rolled back to 2.1.3 and now for some reason it's taking an **age** to try and complete, instead of under 2 mins it's not 13mins plus and I simply cancelled...
[https://github.com/dcaddick/gsd_public/actions/runs/3936269907/jobs/6732667943](url)

![image](https://user-images.githubusercontent.com/19640455/212819089-8ebbc901-4379-4099-a9b6-5e281550a3ae.png)

**Comment by athackst** [comment]
WTF needs pandas?  That's a rather heavy-weight requirement for document building.

The image I use for the action is based on apk to keep it light/quick, maybe pandas needs to be built from source because it's not available as a pre-built?

You might be better served with your own workflow instead of using the action?

```yaml
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: pip
      - name: Setup
        run: |
          python -m pip install --upgrade pip
         pip install -r requirements.txt
      - name: Deploy docs
         run: |
           git fetch origin gh-pages --depth=1 || echo -e "skipping fetch"
           mkdocs gh-deploy
```

**Comment by dcaddick** [comment]
I'm glad you said that - cause this is doing my head in - looks like it's now going round in circles... ;-)
[https://github.com/dcaddick/gsd_public/actions/runs/3936424193](url)
currently just tipped over the 56 min mark

**Comment by dcaddick** [comment]
So I can only assume at this stage I'm disappearing down some almighty rabbit hole?

I'm quite happy to reset back to basics and simply see if I can get the Plugins working using any other method - I certainly didn't want to become a monumental "time suck" that this has started to become ;-(

[Invalid workflow file: .github/workflows/MakeDocsAction.yaml#L11](https://github.com/dcaddick/gsd_public/actions/runs/3936808471/workflow)
You have an error in your yaml syntax on line 11

So this appears to be cache: pip?

```
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: pip
      - name: Setup
        run: |
          python -m pip install --upgrade pip
         pip install -r requirements.txt
      - name: Deploy docs
         run: |
           git fetch origin gh-pages --depth=1 || echo -e "skipping fetch"
           mkdocs gh-deploy
```

**Comment by athackst** [comment]
It's more likely the spacing errors on the lines below it.

```yaml
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: pip
      - name: Setup
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Deploy docs
        run: |
          git fetch origin gh-pages --depth=1 || echo -e "skipping fetch"
          mkdocs_simple_gen --deploy
```

I'm also pretty sure those git-xx plugins aren't compatible with this one.  This plugin builds docs in a tmp directory which would strip all of the git info.

You may be better served just doing what mkdocs expects and placing everything in a /docs folder.

And yes, it's likely a rabbit hole.  I'd try to build it locally if you can.

**Comment by dcaddick** [comment]
Thanks, stripped it all back & removed all PIP commands + removed all non-essential Plug-ins from reqs.txt
Now back to building in under 2 mins - I have "isolated the errant Plugin" to being either:
table-reader or mermaid2 ...?
One of those appears to "pull in" Pandas? & blows the time out or loops...

**Comment by timvink** [comment]
> WTF needs pandas? 

Hi, author of `mkdocs-table-reader-plugin` here, yes, that one uses `pandas`, which in turn uses `numpy` which in turn is not ready for python 3.11 _yet_.  

> That's a rather heavy-weight requirement for document building.

For document building yes, but I'm assuming when you're working with CSVs / table data and python that you are using pandas anyway.

> This plugin builds docs in a tmp directory which would strip all of the git info.

Would it be possible to copy the `.git` folder to the `tmp/` folder also? ` mkdocs-simple-plugin` seems to be getting some traction (awesome!) and users are opening issues on my git plugins (example [here](https://github.com/timvink/mkdocs-git-authors-plugin/issues/69)).  Happy to open a separate issue for this one if you want.

**Comment by athackst** [comment]
>Would it be possible to copy the .git folder to the tmp/ folder also?  mkdocs-simple-plugin seems to be getting some traction (awesome!) and users are opening issues on my git plugins (example https://github.com/timvink/mkdocs-git-authors-plugin/issues/69). Happy to open a separate issue for this one if you want.

It's already possible to copy any folder directly into the output.

`include_extensions` uses a glob file pattern so `.git/**` should copy everything in the .git directory.  I'm in the process of renaming that input so that functionality is more apparent.

I'm not positive that just doing that will work appropriately though.

I've already updated the docker to use ubuntu instead of alpine which should solve the compile issue #468

**Comment by dcaddick** [comment]
> .git/**

I've just given that a try - but might have the syntax incorrect?

Deploying docs to gh-pages
ERROR    -  Config value 'plugins': Invalid Plugins configuration
Aborted with 1 Configuration Errors!
[https://github.com/dcaddick/gsd_public/actions/runs/4119980229/jobs/7114245927](url)

What I used was:
```
  #- simple
  - simple:
    include_extensions: [".git/**"]
```

**Comment by athackst** [comment]
hm, I'll check it out

**Comment by athackst** [comment]
#481 and #482 should help you out.

That looks like the right setting in config

**Comment by dcaddick** [comment]
I have this set in mkdocs.yml as:

```
  - simple:
      include_extensions:
      - ".git/**"
```

This now flows thru without error at Build time - however I'm not sure it's fixed the original problem?
When I look thru the logging it looks like there is still a problem with the git-authors-plugin?
And it looks like it's still being built in the tmp folder?

Have I managed to do something wrong?
```
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /github/workspace/site
WARNING  -  [git-authors-plugin] /tmp/mkdocs_simple_4g5lfiyk/README.md has not been committed yet. Lines are not counted
WARNING  -  [git-authors-plugin] /tmp/mkdocs_simple_4g5lfiyk/ASD.md has not been committed yet. Lines are not counted
WARNING  -  [git-authors-plugin] /tmp/mkdocs_simple_4g5lfiyk/AssumedKnowledge.md has not been committed yet. Lines are not counted
WARNING  -  [git-authors-plugin] /tmp/mkdocs_simple_4g5lfiyk/Author.md has not been committed yet. Lines are not counted
```

**Comment by athackst** [comment]
Yeah, I'm pretty sure the copy into tmp is not going to work with the git plugin.

I have an experimental branch that uses on_files instead of changing the docs directory https://github.com/athackst/mkdocs-simple-plugin/tree/feat/on-files

You can try it in an action by pointing to the commit

```yaml
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and push docs
        uses: athackst/mkdocs-simple-plugin@11e81727cdfac8b224da1bb486d7072da6c5cd5d
```

**Comment by dcaddick** [comment]
Thanks, tested and run the action here

https://github.com/dcaddick/gsd_public/actions/runs/4213295511/jobs/7312919312

It does appear to use the git, before having an error, looks like I need to step into trying to run this locally as a docker image later today

**Comment by athackst** [comment]
You should remove the include_extensions: [".git/**"] line from your mkdocs.yml file. With this branch you shouldn't need it.

**Comment by dcaddick** [comment]
Doh! Apologies

Rerun without error, but there does appear to be some indications that the git didn't come thru?

https://github.com/dcaddick/gsd_public/actions/runs/4213383482

![image](https://user-images.githubusercontent.com/19640455/219903221-af4c03be-4518-4a64-9f0b-0c21935884fa.jpeg)

**Comment by dcaddick** [comment]
Checking further in the published pages I can now see that at the bottom of each page it is not correctly reporting the "last update" date of each individual page.

It's still a little early on Sunday morning here in Perth, but will dive in a bit deeper today to have a look, thanks for your persistence

**Comment by athackst** [comment]
Looks like there's a deprecation warning on the git-authors-plugin. That is probably triggered by python 3.11. You could see if the author has an update for that one. 

I'm not sure why the other one says it can't find git. Git should be installed in the dockerfile and accessible. None of the files are being moved so git should be reporting the correct status. My best guess is that it might be looking for the git folder a folder above where the docs folder is located?  You might want to try adding 'docs_dir: docs' to your mkdocs.yml file.

**Comment by dcaddick** [comment]
This experimental branch looks good to me

`> uses: athackst/mkdocs-simple-plugin@11e81727cdfac8b224da1bb486d7072da6c5cd5d`

At the bottom of the pages I am now successfully seeing the created & updated date appear

![image](https://user-images.githubusercontent.com/19640455/219956111-954056e1-4020-4c89-b561-c0aa60c6f1e4.jpeg)

**Comment by dcaddick** [comment]
Hi Allison,

Just checking as still pointing at the experimental branch - looks like you are testing Debian?
I guess I'll leave it a week or so before switching back to the updated default branch?

Regards,
Dave C
